development:
  adapter: postgresql
  encoding: unicode
  database: agilencr_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: agilencr_test
  pool: 5
  username: postgres
  password: postgres
